---
apiVersion: actions.github.upbound.io/v1alpha1
kind: ActionsSecret
metadata:
  name: {{ .Release.Name }}-kubeconfig-previews
spec:
  forProvider:
    plaintextValueSecretRef:
      key: kubeconfig
      name: kubeconfig-previews
      namespace: {{ .Release.Namespace }}
    repositorySelector:
      matchLabels:
        owner: {{ .Values.github.organization }}
        repo: {{ .Values.github.repository }}
    secretName: github-creds
